development:
  dir_mode: script
  dir: ../../log/dev
  multiple: false
  backtrace: true
  monitor: false
  ontop: true
production:
  dir_mode: script
  dir: ../../log/prod
  multiple: false
  backtrace: true
  monitor: false
  ontop: false