defaults: &defaults
  # app_key: 12000221
  # secret_key: 003836cbc22eb4294d7986a538fc3853
  app_key: 12060575
  secret_key: afd5f5c495f921f9e42470db179cfd1f
  # secret_key: sandbox495f921f9e42470db179cfd1f
  # is_sandbox: true
  taobaoke_pid: 10894158
  taobaoke_nick: usedcar
  # taobaoke_pid: mm_10894158_0_0
  is_sandbox: false
development:
  <<: *defaults
  # is_sandbox: true # If true, it will work under the sandbox environment(tbsandbox.com, not taobao.com).
  use_curl: false # If true, it will use gem "patron" as the REST client, then you should install gem "patron" first and bundle it in your rails application.

test:
  <<: *defaults
  # is_sandbox: ture
  use_curl: false

production:
  <<: *defaults
  app_key: 12060575
  secret_key: afd5f5c495f921f9e42470db179cfd1f
  is_sandbox: false
  use_curl: false
back:
  app_key: 21061174
  secret_key: c7a31d7a50e10d0a254a5fd6645a87c5
front:
  app_key: 21324080
  secret_key: 9d3d97a78a2046b1640c6d67f9245a51
